-- MySQL Script generated by MySQL Workbench
-- Qui 23 Ago 2018 15:15:20 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema itools
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `itools` ;

-- -----------------------------------------------------
-- Schema itools
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `itools` DEFAULT CHARACTER SET utf8 ;
USE `itools` ;

-- -----------------------------------------------------
-- Table `itools`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itools`.`customer` ;

CREATE TABLE IF NOT EXISTS `itools`.`customer` (
  `cpf` VARCHAR(11) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `state` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `idcustomers_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `itools`.`phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itools`.`phone` ;

CREATE TABLE IF NOT EXISTS `itools`.`phone` (
  `customer_cpf` VARCHAR(11) NOT NULL,
  `phone_number` VARCHAR(12) NOT NULL,
  `type` ENUM('mobile', 'home', 'work', 'fax') NOT NULL,
  PRIMARY KEY (`customer_cpf`, `phone_number`),
  CONSTRAINT `customer_cpf`
    FOREIGN KEY (`customer_cpf`)
    REFERENCES `itools`.`customer` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
